### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-a-javascript-application

### ISSUE THREAD

**Issue by hakunin** [airbrake/airbrake-docs#151]
I want to know how to report error without manually raising it.

For instnace instead of this:

```
try {
  throw new Error('My error');
} catch (e) {
  Airbrake.notify(e);
}
```

I would like to do this
```
Airbrake.notify('My error')
```

In a JS app, it doesn't make sense to let an exception loose and break user's UI interaction.

**Comment by thompiler** [comment]
Howdy @hakunin,

If you'd like to report a message to Airbrake, you can use the method you mention (ie: `Airbrake.notify('My error');`) because the `notify` method takes strings as well as errors as input. 

Here's an example from the airbrake-js repo:

https://github.com/airbrake/airbrake-js/blob/aa7bce8e6d7375d59b049fdbb14da2b98cd8ba68/examples/legacy/app.js#L7

Have you had any issues trying what you suggested?

**Comment by hakunin** [comment]
Thanks, if its reporting the backtrace as well, then thats great. (if not then I still have to throw and catch).

I didn't notice it documented anywhere though.

**Comment by thompiler** [comment]
Thanks @vmihailenco! 

@hakunin let us know if you have anymore questions.
