### ISSUE TITLE
RE: /airbrake-faq/how-do-global-error-types-work

### ISSUE THREAD

**Issue by kreba** [airbrake/airbrake-docs#41]
The link in the following line is dead:
A full list of grouping options is available in our grouping doc.

I was expecting it to point to 
https://airbrake.io/docs/airbrake-faq/configuring-error-grouping-settings/
This FAQ page provides an excellent expanation of how grouping can be tweaked.

**Comment by kreba** [comment]
On a related note:

Sadly, the help links on the configuration page (/projects/1/edit) don't point to the FAQ but to 
https://airbrake.io/docs/api/#global-grouping
which in turn ends up showing me
https://airbrake.io/docs/api/#create-ios-crash-report-v3
which does not provide specifics about what the individual settings do. 

The FAQ is much better.

**Comment by thompiler** [comment]
Howdy @kreba 

Thanks for letting us know. We'll update the link in the doc. About the section issue, I see the correct section in our API docs when I visit https://airbrake.io/docs/api/#global-grouping but it will be in the center since it's close to the bottom of the page:

<img width="1000" alt="screen shot 2016-09-22 at 5 41 46 pm" src="https://cloud.githubusercontent.com/assets/2172513/18770528/f0449aea-80eb-11e6-97e0-55f21cbc2e38.png">

That said, I like the FAQ doc better too.  It is more in-depth.  I'll open an issue in our internal repo to update the links.

**Comment by kreba** [comment]
Thank you for your quick reply :)

Aaah, so that's what happened. My screen is fairly big. So when I follow the link to the grouping API doc, the iOS crash reports v3 will be at the top of the page. The table of contents on the left then self-updates accordingly. That completely diverted my attention away from the grouping doc and to that iOS doc.

On some websites you get that flashing effect. For example, when you follow a link to a certain answer on Stackoverflow, the whole thread is shown. But the requested answer is scrolled into view and has a yellow background that slowly fades. This yellow flashing directs your attention to the element you requested. Maybe something like that would be a good idea for your docs?

Cheers

**Comment by thompiler** [comment]
>On some websites you get that flashing effect. For example, when you follow a link to a certain answer on Stackoverflow, the whole thread is shown. But the requested answer is scrolled into view and has a yellow background that slowly fades. This yellow flashing directs your attention to the element you requested. Maybe something like that would be a good idea for your docs?

Interesting idea! Thanks for the feedback. I'll let the team know.

Let us know if you have any other questions or issues.
