### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-an-ios-application

### ISSUE THREAD

**Issue by sgubler** [airbrake/airbrake-docs#59]
The README.md is out of date for installing/using Airbrake on iOS 10/Xcode 8 and Cocoapods 1.1.1

Firstly ABCrashReporter.h need the second import statement changed to `#import "CrashReporter.h"`

Secondly the AppDelegate.swift syntax is:

ABNotifier.start(withAPIKey: "API Key", projectID: "Project ID", environmentName: ABNotifierAutomaticEnvironment, useSSL: true)

**Comment by stuartmoore1023** [comment]
Thanks for reporting this. Since this is concerning the documentation from our iOS notifier and not the contents of our help docs site, could you file this issue in the related issues section for that notifier? You can create a new issue for that repository here:
https://github.com/airbrake/airbrake-ios/issues

**Comment by kyrylo** [comment]
https://github.com/airbrake/airbrake-ios/issues/79
