### ISSUE TITLE
RE: /integrations/slack

### ISSUE THREAD

**Issue by LouisSayers** [airbrake/airbrake-docs#81]
I'm currently hosted on Heroku, and trying to add Airbrake as a Slack integration. 

In order to do this, Slack docs say to:

> Click on Slack in the list of integrations, add https://hooks.slack.com/services/x/y/z as the Slack webhook, and choose your notification settings. Press the Save button when you're done. 

When I go to my Airbrake settings and click 'integrations', I get the message "Please manage your plan through your host".

So, I guess I'm unable to add Airbrake as a Slack integration if I'm hosted on Heroku?

**Comment by shifi** [comment]
Hi Louis,

Are you on a free Heroku plan? If so, we don't offer integrations for free plans. To use integrations you have to upgrade your account and since you're on Heroku you saw the message "Please manage your plan through your host".

If you are not on a free plan, please send me your Airbrake subdomain name so I can investigate.
Thank you.

**Comment by LouisSayers** [comment]
Hi Shifi, 

Thanks a lot for your quick response. Yes, I'm on the free airbrake plan atm which will be why it's not working. Thanks for the info!

**Comment by kyrylo** [comment]
Please disregard, I can see that we already have an internal issue about this.
